### ISSUE TITLE
drvGPIO development

### ISSUE THREAD

**Issue by AksonovSergei** [AksonovSergei/NureEmbClass_2016#4]

**Comment by NikolaiGerasimenko** [comment]
I propose to call the LED pins as follows:
	pinLed_Heartbeat,
	pinLed_Red,
	pinLed_Yellow,
	pinLed_Green1,
	pinLed_Green2,
	pinAmount

And type of this list: drvGPIO_List_t;

**Comment by KostiantynAndrieiev** [comment]
Ok, I'll do it. The code will be pushed to GitHub today by 23.00.

**Comment by KostiantynAndrieiev** [comment]
drvGPIO is done. Unfortunately, it took more time that promised.

**Comment by KostiantynAndrieiev** [comment]
But some note:
Since I don't know the pinout of the board we're working with, I initialized only default NUCLEO pins: PA5 for the LED, PC13 for the button.

**Comment by NikolaiGerasimenko** [comment]
For the developed board:
                {PORT_A, 5},		// pinLedHeartbeat
		{PORT_C, 0},		// pinLed_RED
		{PORT_C, 1},		// pinLed_YELLOW
		{PORT_C, 2},		// pinLed_GREEN1
		{PORT_C, 3},		// pinLed_GREEN2
		{PORT_B, 13},		// pinKey_1
		{PORT_B, 14},		// pinKey_2
		{PORT_B, 15}		// pinKey_3

**Comment by KostiantynAndrieiev** [comment]
Ok, thanks. I'll fix it.
It turns out I have different pinout on my dev board.

**Comment by LorinsBeard** [comment]
As I can see, you put all information of Ports and Pins of each led or button inside your driver. So, if you want to add new led in your project, you need make declaration of this pin in drvLeds and in drvGPIO, am I right? Or to change port or pin of LED, you have to go to the drvGPIO, what is not so obvious. I think this approach is not very usable, because you can make mistake of declaration in one of the tables in both drivers. For example, in drvGPIO pinLed_YELLOW on the third place, and on the second place in drvLED. 
Maybe functions of drvGPIO must take PORT and PIN by parameters? Its more clearly and reduce possibility of error.
And one more thing - why function drvGPIO_Init() initialize only 2 pins??

**Comment by KostiantynAndrieiev** [comment]
The second question I am up to answer first of all: only 2 pins because at the moment of 'coding' drvGPIO I didn't know the exact pinout of the dev board we're dealing with. Now that I've collected that information I can add a variety of other essential pins..
And now to the first question of yours. I assumed that one uses drvGPIO for initialization, there the IDs of each pin are also set. And all other drivers use this info provided by drvGPIO, instead of having their own, otherwise, I agree with you, that can cause loads of errors..
PORT and PIN by parameters - a perfect idea, though already implemented in HAL.

**Comment by KostiantynAndrieiev** [comment]
The reason, I don't actually like the idea of PORT&PIN-as-parameters is that it decreases the readability of the code..

**Comment by AksonovSergei** [comment]
Hello guys. 
You faced with very often issue related to the drvGPIO parameters. You forgot about case when not only GPIO outputs of MCU are used. I provided example with a shift register - do you remember?

So, correct case when drvGPIO has parameter as pin name. It should be name from real world like HeaterRelay, PowerLED etc. It is not a problem of business logic to know which hardware port and pin are used for current output.

**Comment by KostiantynAndrieiev** [comment]
Finally done.
